version: '3.8'

services:
  sqlite:
    image: keinos/sqlite3
    container_name: warehouse_sqlite
    platform: linux/amd64
    ports:
      - "8191:8191"
    volumes:
      - ./db:/db
    working_dir: /workspace
    command: ["tail", "-f", "/dev/null"]
